### ISSUE TITLE
When sending data with this data model to QuantumLeap, persisting data to Timescale fails.

### ISSUE THREAD

**Issue by ilarimikkonen** [smart-data-models/dataModel.Building#5]
```
"occupier": [
    "9830f692-7677-11e6-838b-4f9fb3dc5a4f"
  ],
```
is causing problems. QL [issue](https://github.com/orchestracities/ngsi-timeseries-api/issues/537) for reference.

**Comment by albertoabellagarcia** [comment]
This is not a URI value (it is actually valid but I mean that it has no schema, host or protocol) , however,  the context broker does not check types, so I should work. What's the issue then?

**Comment by ilarimikkonen** [comment]
context broker does not check types and it does not care, as it's backed up by Mongo. But QuantumLeap works with Timescale, and  they need to map the values. Now the question is that "are the datamodels supposed to work with Orion and QuantumLeap combination"? Or are they tested and developed only with Orion?

**Comment by albertoabellagarcia** [comment]
Checking this with QL experts...

**Comment by albertoabellagarcia** [comment]
We check with Orion, and it is true that currently, we are not checking with QL.
